name: "Build container image"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Cuild container Images
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/ui/yarn.lock/*') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn hack
        run: mkdir -p /home/runner/.cache/yarn/v6
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - name: Install dependencies
        run: yarn install # do not use "--frozen-lockfile" here
      - name: Check yarn.lock
        run: |
          echo 'If stip step fails, the yarn.lock does not conform the package.json, run "yarn update-update-frozen_node_modules"' 
          git diff --quiet
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      # Add tests here
      - name: Clean
        # The output of the build is not needed, let's focus on the container image instead
        run: |
          yarn clean
          rm -rf ./node_modules
      - name: Prepare podman env
        run: |
          sudo apt-get -y install podman
          mkdir -p ~/.docker
      - name: Housekeeping clean old podman resources
        continue-on-error: true
        id: housekeeping
        run: |
          podman images
          DATE=$(date --date="21 days ago" +"%Y-%m-%d")
          podman rm --force $(podman ps -a -q --filter until=$DATE)
          podman rmi --force $(podman images -a -q)
          podman images
      - name: Podman build
        run: |
          podman build . -f ./Dockerfile -t quay.io/mlibra/console-plugin-vsphere:${{ github.sha }}
      # The image is recently not pushed anywhere
